language: php

php:
  - 5.5
  - 5.6

install:
  - composer install --prefer-source

before_script:
  - if [ $TRAVIS_PHP_VERSION = '5.6' ]; then PHPUNIT_FLAGS="--coverage-clover=coverage.clover"; fi
  - vendor/bin/phpcs src tests --standard=vendor/zenify/coding-standard/src/ZenifyCodingStandard/ruleset.xml

script:
  - phpunit $PHPUNIT_FLAGS

after_script:
  - if [ ! -z "$PHPUNIT_FLAGS" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
